# Generated by Django 6.0.4 on 2026-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(choices=[('antivirus', 'Antivirus'), ('firewall', 'Firewall'), ('ids_ips', 'IDS/IPS'), ('encryption', 'Encryption'), ('other', 'Other')], max_length=24)),
                ('why_needed', models.TextField()),
                ('how_it_works', models.TextField()),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
