# Generated by Django 6.0.4 on 2026-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensetool',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
