# Generated by Django 6.0.4 on 2026-04-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0002_defensetool_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensetool',
            name='image_url',
        ),
        migrations.AddField(
            model_name='defensetool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='defense/'),
        ),
    ]
