# Generated by Django 6.0.4 on 2026-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0003_remove_defensetool_image_url_defensetool_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defensetool',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Goranyş guraly', 'verbose_name_plural': 'Goranyş gurallary'},
        ),
        migrations.AlterField(
            model_name='defensetool',
            name='category',
            field=models.CharField(choices=[('antivirus', 'Antiwirus'), ('firewall', 'Brandmauer (Firewall)'), ('ids_ips', 'IDS/IPS'), ('encryption', 'Şifrlemek'), ('other', 'Başga')], max_length=24, verbose_name='Kategoriýasy'),
        ),
        migrations.AlterField(
            model_name='defensetool',
            name='how_it_works',
            field=models.TextField(verbose_name='Nähili işleýär?'),
        ),
        migrations.AlterField(
            model_name='defensetool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='defense/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='defensetool',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='defensetool',
            name='why_needed',
            field=models.TextField(verbose_name='Näme üçin gerek?'),
        ),
    ]
