# Generated by Django 6.0.4 on 2026-04-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0004_alter_defensetool_options_alter_defensetool_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Ady')),
            ],
            options={
                'verbose_name': 'Goranyş kategoriýasy',
                'verbose_name_plural': 'Goranyş kategoriýalary',
            },
        ),
        migrations.AlterField(
            model_name='defensetool',
            name='category',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Kategoriýasy'),
        ),
        migrations.AddField(
            model_name='defensetool',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='defense.defensecategory', verbose_name='Kategoriýa (Täze)'),
        ),
    ]
