# Generated by Django 6.0.4 on 2026-04-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0005_defensecategory_alter_defensetool_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensetool',
            name='category',
        ),
        migrations.RenameField(
            model_name='defensetool',
            old_name='category_new',
            new_name='category',
        ),
    ]
