# Generated by Django 6.0.4 on 2026-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsitem_image_url_newsitem_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Täzelik', 'verbose_name_plural': 'Täzelikler'},
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('attack', 'Hüjüm'), ('data_breach', 'Maglumat syzyşmasy'), ('ai_security', 'AI howpsuzlygy'), ('other', 'Başga')], default='other', max_length=32, verbose_name='Kategoriýasy'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=models.TextField(verbose_name='Mazmuny'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Döredilen wagty'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='published_at',
            field=models.DateField(verbose_name='Çap edilen senesi'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sözbaşy'),
        ),
    ]
