# Generated by Django 6.0.4 on 2026-04-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsitem_options_alter_newsitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Ady')),
            ],
            options={
                'verbose_name': 'Täzelik kategoriýasy',
                'verbose_name_plural': 'Täzelik kategoriýalary',
            },
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Kategoriýasy'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory', verbose_name='Kategoriýa (Täze)'),
        ),
    ]
