# Generated by Django 6.0.4 on 2026-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('transport', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=16)),
                ('service_name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('well_known', 'Well-known'), ('registered', 'Registered'), ('dynamic_private', 'Dynamic/Private')], default='well_known', max_length=32)),
                ('what_it_does', models.TextField()),
                ('where_used', models.TextField(blank=True)),
                ('security_risks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number', 'transport', 'service_name'],
                'constraints': [models.UniqueConstraint(fields=('number', 'transport'), name='unique_port_number_transport')],
            },
        ),
    ]
