# Generated by Django 6.0.4 on 2026-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['number', 'transport', 'service_name'], 'verbose_name': 'Port', 'verbose_name_plural': 'Portlar'},
        ),
        migrations.AlterField(
            model_name='port',
            name='category',
            field=models.CharField(choices=[('well_known', 'Meşhur (Well-known)'), ('registered', 'Hasaba alnan (Registered)'), ('dynamic_private', 'Dinamyk/Hususy')], default='well_known', max_length=32, verbose_name='Kategoriýasy'),
        ),
        migrations.AlterField(
            model_name='port',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Port belgisi'),
        ),
        migrations.AlterField(
            model_name='port',
            name='security_risks',
            field=models.TextField(blank=True, verbose_name='Howpsuzlyk töwekgelçilikleri'),
        ),
        migrations.AlterField(
            model_name='port',
            name='service_name',
            field=models.CharField(max_length=64, verbose_name='Hyzmatyň ady'),
        ),
        migrations.AlterField(
            model_name='port',
            name='transport',
            field=models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=16, verbose_name='Ulag protokoly'),
        ),
        migrations.AlterField(
            model_name='port',
            name='what_it_does',
            field=models.TextField(verbose_name='Bu näme?'),
        ),
        migrations.AlterField(
            model_name='port',
            name='where_used',
            field=models.TextField(blank=True, verbose_name='Nirede ulanylýar?'),
        ),
    ]
