# Generated by Django 6.0.4 on 2026-04-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_portcategory_alter_port_category_port_category_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='category',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='category_new',
            new_name='category',
        ),
    ]
