# Generated by Django 6.0.4 on 2026-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('application', 'Application'), ('network', 'Network')], max_length=32)),
                ('purpose', models.TextField()),
                ('how_it_works', models.TextField()),
                ('real_world_use', models.TextField(blank=True)),
                ('security_notes', models.TextField(blank=True)),
                ('highlight_dns', models.BooleanField(default=False, help_text='Enable for DNS to show extra emphasis on the page.')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
