# Generated by Django 6.0.4 on 2026-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Protokol', 'verbose_name_plural': 'Protokollar'},
        ),
        migrations.AlterField(
            model_name='protocol',
            name='category',
            field=models.CharField(choices=[('transport', 'Ulag'), ('application', 'Amaly'), ('network', 'Tor')], max_length=32, verbose_name='Kategoriýasy'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='highlight_dns',
            field=models.BooleanField(default=False, help_text='DNS-i sahypada has aýdyň görkezmek üçin işlediň.', verbose_name='DNS aýratynlygy'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='how_it_works',
            field=models.TextField(verbose_name='Nähili işleýär?'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='purpose',
            field=models.TextField(verbose_name='Maksady'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='real_world_use',
            field=models.TextField(blank=True, verbose_name='Amaly ulanylyşy'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='security_notes',
            field=models.TextField(blank=True, verbose_name='Howpsuzlyk bellikleri'),
        ),
    ]
