# Generated by Django 6.0.4 on 2026-04-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_alter_protocol_options_alter_protocol_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Ady')),
            ],
            options={
                'verbose_name': 'Protokol kategoriýasy',
                'verbose_name_plural': 'Protokol kategoriýalary',
            },
        ),
        migrations.AlterField(
            model_name='protocol',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Kategoriýasy'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols', to='protocols.protocolcategory', verbose_name='Kategoriýa (Täze)'),
        ),
    ]
