# Generated by Django 6.0.4 on 2026-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyevent',
            options={'ordering': ['order', 'year_start'], 'verbose_name': 'Taryhy waka', 'verbose_name_plural': 'Taryhy wakalar'},
        ),
        migrations.AlterModelOptions(
            name='homehighlight',
            options={'ordering': ['order'], 'verbose_name': 'Esasy maglumat', 'verbose_name_plural': 'Esasy maglumatlar'},
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='description',
            field=models.TextField(verbose_name='Mazmuny'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tertibi'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Sözbaşy'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='year_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gutarýan senesi (ýyl)'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='year_start',
            field=models.PositiveIntegerField(verbose_name='Başlan senesi (ýyl)'),
        ),
        migrations.AlterField(
            model_name='homehighlight',
            name='body',
            field=models.TextField(verbose_name='Mazmuny'),
        ),
        migrations.AlterField(
            model_name='homehighlight',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tertibi'),
        ),
        migrations.AlterField(
            model_name='homehighlight',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Sözbaşy'),
        ),
    ]
