# Generated by Django 6.0.4 on 2026-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('attack_type', models.CharField(choices=[('phishing', 'Phishing'), ('ddos', 'DDoS'), ('malware', 'Malware'), ('mitm', 'Man-in-the-middle'), ('other', 'Other')], default='other', max_length=24)),
                ('what_it_does', models.TextField()),
                ('how_it_works', models.TextField()),
                ('goal', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['attack_type', 'name'],
            },
        ),
    ]
