# Generated by Django 6.0.4 on 2026-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
