# Generated by Django 6.0.4 on 2026-04-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0002_attack_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='image_url',
        ),
        migrations.AddField(
            model_name='attack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attacks/'),
        ),
    ]
