# Generated by Django 6.0.4 on 2026-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0003_remove_attack_image_url_attack_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attack',
            options={'ordering': ['attack_type', 'name'], 'verbose_name': 'Hüjüm', 'verbose_name_plural': 'Hüjümler'},
        ),
        migrations.AlterField(
            model_name='attack',
            name='attack_type',
            field=models.CharField(choices=[('phishing', 'Fişing'), ('ddos', 'DDoS hüjümi'), ('malware', 'Zyýanly programma'), ('mitm', 'Aralygyndaky adam (MITM)'), ('other', 'Başga')], default='other', max_length=24, verbose_name='Görnüşi'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='example',
            field=models.TextField(blank=True, verbose_name='Mysal'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='goal',
            field=models.TextField(blank=True, verbose_name='Maksady'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='how_it_works',
            field=models.TextField(verbose_name='Nähili işleýär?'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attacks/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='prevention',
            field=models.TextField(blank=True, verbose_name='Goranyş'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='what_it_does',
            field=models.TextField(verbose_name='Bu näme?'),
        ),
    ]
