# Generated by Django 6.0.4 on 2026-04-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0004_alter_attack_options_alter_attack_attack_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Ady')),
            ],
            options={
                'verbose_name': 'Hüjüm kategoriýasy',
                'verbose_name_plural': 'Hüjüm kategoriýalary',
            },
        ),
        migrations.AlterField(
            model_name='attack',
            name='attack_type',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Görnüşi'),
        ),
        migrations.AddField(
            model_name='attack',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacks', to='attacks.attackcategory', verbose_name='Kategoriýa (Täze)'),
        ),
    ]
