# Generated by Django 6.0.4 on 2026-04-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0005_attackcategory_alter_attack_attack_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='attack_type',
        ),
        migrations.RenameField(
            model_name='attack',
            old_name='category_new',
            new_name='attack_type',
        ),
    ]
