# Generated by Django 6.0.4 on 2026-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('audience', models.TextField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=128)),
                ('author_bio', models.TextField(blank=True)),
                ('future_plans', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Project info',
                'verbose_name_plural': 'Project info',
            },
        ),
    ]
