# Generated by Django 6.0.4 on 2026-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinfo',
            options={'verbose_name': 'Taslama maglumaty', 'verbose_name_plural': 'Taslama maglumatlary'},
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='audience',
            field=models.TextField(blank=True, verbose_name='Diňleýjiler (Auditoriýa)'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='author_bio',
            field=models.TextField(blank=True, verbose_name='Awtor barada maglumat'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='author_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Awtoryň ady'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='future_plans',
            field=models.TextField(blank=True, verbose_name='Gelejekki meýiller'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='goal',
            field=models.TextField(verbose_name='Maksady'),
        ),
    ]
